[build]
  publish = "."
  functions = "netlify/functions"

# Przekierowanie /api/* na Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Obsługa SPAs jeśli dodasz routing później
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
