
[build]
  publish = "public"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[template.environment]
  OPENAI_API_KEY = "sk-..."
  OPENAI_MODEL = "gpt-4o-mini"
