[build]
  publish = "."
  command = ""

[functions]
  directory = "."
  node_bundler = "esbuild"
  included_files = ["*.js"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/ziomek"
  status = 200
  force = true

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
