
[build]
  publish = "public"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[template.environment]
  GROQ_API_KEY = "gsk_..."
  GROQ_MODEL = "llama-3.1-70b-versatile"
